name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install htmlhint
      run: npm install -g htmlhint

    - name: Lint HTML
      run: htmlhint index.html
