name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Verify HTML
      run: |
        if [ -f index.html ]; then
          echo "index.html exists."
        else
          echo "index.html is missing!" && exit 1
        fi
